### ISSUE TITLE
KeyError: Delete

### ISSUE THREAD

**Issue by mhartington** [kristijanhusak/defx-git#2]
Hi there! Looks like there's an error that happens when you delete some files in git.

```
Error detected while processing function defx#_do_action[6]..defx#util#rpcrequest[15].._defx_do_action[1]..remote#define#request:
line    2:
error caught in request handler '/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx:function:_defx_do_action [['drop', [], {'columns': 'mark:filename:typ
e', 'auto_cd': False, 'prev_bufnr': 2, 'resume': False, 'listed': False, 'new': False, 'fnamewidth': 100, 'direction': '', 'winheight': 0, 'profile': False, 's
earch': '', 'buffer_name': 'default', 'winwidth': 0, 'split': 'no', 'cursor': 7, 'toggle': False}]]':
Traceback (most recent call last):
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/__init__.py", line 41, in do_action
    self._rplugin.do_action(args)
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/rplugin.py", line 37, in do_action
    view.do_action(args[0], args[1], args[2])
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/view.py", line 324, in do_action
    ret = action.do_action(self, defx, action_name, context)
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/action.py", line 38, in do_action
    action.func(view, defx, context)
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/action.py", line 236, in _drop
    view.cd(defx, str(path), context.cursor)
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/view.py", line 281, in cd
    self.redraw(True)
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/view.py", line 235, in redraw
    for x in self._candidates
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/view.py", line 235, in <listcomp>
    for x in self._candidates
  File "/Users/mhartington/GitHub/defx.nvim/rplugin/python3/defx/view.py", line 251, in get_columns_text
    text += column.get(context, candidate)
  File "/Users/mhartington/.config/nvim/.cache/init.vim/.dein/rplugin/python3/defx/column/git.py", line 52, in get
    self.indicators[self.get_indicator_name(entry[0], entry[1])]
KeyError: 'Deleted'
```

Will look into this, but figured I'd pass it along.

Cheers!

**Comment by kristijanhusak** [comment]
How exactly did you delete a file, with `git rm` or directly with `rm` ?
Exact steps to reproduce would be great.

**Comment by mhartington** [comment]
Ahh, seems to be an error on my end. Customized the indicators but did not include the `Deleted` mark. Sorry for the noise.
